openapi: 3.1.0
info:
  title: createFromBlank
  version: '1.0'
servers:
  - url: api/v2
    description: ''
paths:
  /user/getUser:
    parameters: []
    get:
      summary: ''
      operationId: get-users-userId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  address:
                    type: string
                  id:
                    type: number
                  phone:
                    type: string
                  userName:
                    type: string
      parameters:
        - schema:
            type: number
          in: header
          name: userId
        - schema:
            type: string
          in: header
          name: address
  /user/getUsrList:
    get:
      summary: get user list
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  address:
                    type: string
                  id:
                    type: number
                  phone:
                    type: string
                  userName:
                    type: string
      operationId: get-user-getUsrList
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        address:
          type: string
        id:
          type: number
        phone:
          type: string
        userName:
          type: string
      x-internal: false
  requestBodies:
    temp:
      content:
        application/json:
          schema:
            type: object
