openapi: 3.1.0
info:
  title: createFromBlank
  version: '1.0'
servers:
  - url: api/v2
    description: ''
paths:
  /user/getUser:
    parameters: []
    get:
      summary: ''
      operationId: get-users-userId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  address:
                    type: string
                  id:
                    type: number
                  phone:
                    type: string
                  userName:
                    type: string
              examples:
                example-1:
                  value:
                    address: address-0
                    id: 0
                    phone: '12345678'
                    userName: user1
      parameters:
        - schema:
            type: number
          in: header
          name: userId
        - schema:
            type: string
          in: header
          name: address
  /user/getUsrList:
    get:
      summary: get user list
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  address:
                    type: string
                  id:
                    type: number
                  phone:
                    type: string
                  userName:
                    type: string
              examples:
                example-1:
                  value:
                    - address: address-0
                      id: 0
                      phone: '12345678'
                      userName: user1
        '404':
          description: Not Found
      operationId: get-user-getUsrList
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - address: address-0
          id: 0
          phone: '12345678'
          userName: user1
      properties:
        address:
          type: string
        id:
          type: number
        phone:
          type: string
        userName:
          type: string
      x-internal: false
  requestBodies: {}
  examples: {}
  parameters: {}
